### ISSUE TITLE
full-gltf-model and animation-mixer

### ISSUE THREAD

**Issue by 2xAA** [gftruj/webzamples#1]
Hi,

I found your component on a [SO answer](https://stackoverflow.com/questions/65367877/how-do-i-get-a-gltfpack-processed-model-to-appear-in-a-frame) - thanks for that, very helpful.

Wanted to mention that [line 35 of index.js](https://github.com/gftruj/webzamples/blob/master/aframe/gltf-packed/index.js#L35) needs to be `self.model` instead of `rootItem` for the animation-mixer component to work.

**Comment by gftruj** [comment]
Glad I could help, and thanks for the info - I'll look into it once I'm back from work.

**Comment by gftruj** [comment]
Accidental "space" while commiting :)
I've applied your hint, but i don't have an animated packed gltf model, so I've made an [example](https://gftruj.github.io/webzamples/aframe/gltf-packed/examples/animated_nonpacked.html) with a standard one.

Thanks for your help! Feel free to comment if you have any other insights :)
