### ISSUE TITLE
Adapting bone-collider to my example

### ISSUE THREAD

**Issue by addy1997** [gftruj/webzamples#6]
Hi @gftruj,

I am trying to adapt your bone-collider example to my robotic arm example ([fiddle](https://jsfiddle.net/adwait3301/u7nxg610/9/)). Actually, I am trying to create a collision event between the robots (their bounding boxes particularly) as shown in the video below. Can I use it for this purpose? 

Note: Both the robots are in **.glTF** format.

 https://user-images.githubusercontent.com/29406906/233684071-6a6c8886-3d71-4d01-a155-3fc0e95e5ad4.mp4

**Comment by gftruj** [comment]
hi, i get a 404 on you fiddle.
Do you want an event emitted when they collide?

**Comment by addy1997** [comment]
Hi @gftruj, 

Sorry! I've updated the link.

**Comment by gftruj** [comment]
Here you can just check if one box intersects the other [fiddle](https://jsfiddle.net/xwamh09L/) (the boxes turn white)

**Comment by addy1997** [comment]
Thank you.
