### ISSUE TITLE
aframe component for cloth simulation

### ISSUE THREAD

**Issue by addy1997** [gftruj/webzamples#8]
Hi @gftruj, 

I am trying to write an [a-frame component](https://jsfiddle.net/adwait3301/26hrLbp0/155/)(Please refer line 67 to 173) to simulate a cloth to cover the manikin/dummy lying on the chair. Although I am importing all the libraries correctly, I am getting this weird error as shown below

![image](https://github.com/gftruj/webzamples/assets/29406906/cff6a75a-6e1b-44cf-b695-5e0f2f7a2030)

I am trying to achieve this [Link](https://jsfiddle.net/adwait3301/nbcg4j6f/)

I am sorry it is not related to your repository in any manner but since you are profound expertise in a-frame, I am asking you. Could you help?

Thanks

**Comment by gftruj** [comment]
I guess the `cloth` function not being called as a method of the component so 'this' is undefined.
https://stackoverflow.com/questions/9822561/why-is-this-in-an-anonymous-function-undefined-when-using-strict
you can bind the variable to the function, or just use a lambda: https://jsfiddle.net/ky0hwbu3/

**Comment by addy1997** [comment]
@gftruj, thank you so much but how do I add the cloth to the scene? I mean how should I use the <a-entity> tag to add the cloth to the scene and create the effect?

Thanks

**Comment by addy1997** [comment]
Hi @gftruj,

Thanks for your comment. In this code, I bound the **cloth()** function inside the **init()** function and used it. However, now I am able to simulate the cloth as an image into the scene using the a-image tag but I don't know where the texture is gone. ([Link to the edited code](https://jsfiddle.net/adwait3301/q36vwhne/187/))
